import { Link } from 'react-router-dom';
import {
  deriveTaskState,
  effectiveDueDate,
  isOverdue,
  type FilterContext,
} from '../../lib/myTasksHelpers';
import type { PermitTask } from '../../lib/database.types';

// Q7.1.b: per-task card render. Mirrors v1's makeTaskCard (index.html
// 5003-5034) under v2's unified schema:
//   - Auto-generated badge (Q5a) — small 🤖 icon when is_auto_generated.
//   - Done indicator (☐ / ✓) is non-interactive in Q7.1.b. Q7.1.c wires
//     the toggle via useUpsertPermitTask.
//   - Address pill links to /project/:id (replaces v1's openProject()
//     navigation hack).

const DAY_MS = 24 * 60 * 60 * 1000;

interface Props {
  task: PermitTask;
  ctx: FilterContext;
  today: Date;
}

export default function TaskCard({ task, ctx, today }: Props) {
  const state = deriveTaskState(task);
  const isDone = state === 'complete';
  const permit = ctx.permitsById.get(task.permit_id);
  const project = permit ? ctx.projectsById.get(permit.project_id) : undefined;

  const permitLabel =
    permit?.type === 'Building Permit' && permit?.nickname
      ? `BP — ${permit.nickname}`
      : permit?.type ?? 'permit';

  const due = effectiveDueDate(task);
  const dueIsPastDue = isOverdue(task, today);
  const dueRel = (() => {
    if (!due) return null;
    const dueMs = new Date(`${due}T12:00:00`).getTime();
    const todayMs = (() => {
      const t = new Date(today);
      t.setHours(0, 0, 0, 0);
      return t.getTime();
    })();
    const days = Math.round((dueMs - todayMs) / DAY_MS);
    if (days < 0) return `${Math.abs(days)}d overdue`;
    if (days === 0) return 'today';
    if (days <= 7) return `${days}d`;
    return null;
  })();

  return (
    <div
      className={`flex items-start gap-2 px-3 py-2 border-b border-border last:border-b-0 ${
        isDone ? 'opacity-60' : ''
      }`}
      data-testid={`mytasks-card-${task.id}`}
    >
      {/* Checkbox — read-only in Q7.1.b. Q7.1.c wires toggle. */}
      <div
        className={`w-3.5 h-3.5 mt-0.5 rounded-sm border flex items-center justify-center flex-shrink-0 ${
          isDone
            ? 'bg-pm border-pm text-white'
            : 'border-border bg-bg'
        }`}
        data-testid={`mytasks-check-${task.id}`}
      >
        {isDone && <span className="text-[9px] leading-none">✓</span>}
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-start gap-1 mb-0.5">
          <span
            className={`text-xs leading-snug font-medium ${
              isDone ? 'line-through text-muted' : 'text-text'
            }`}
            data-testid={`mytasks-text-${task.id}`}
          >
            {task.text}
          </span>
          {task.is_auto_generated && (
            <span
              className="text-[9px] text-dim border border-border rounded px-1 ml-1 flex-shrink-0"
              title="Auto-generated by scraper"
              data-testid={`mytasks-auto-${task.id}`}
            >
              🤖 auto
            </span>
          )}
        </div>

        <div className="flex items-center gap-1.5 flex-wrap mt-0.5">
          {/* Address pill — links to project detail */}
          {project && (
            <Link
              to={`/project/${project.id}`}
              className="text-[10px] text-jv font-bold bg-jv-bg px-1.5 py-0.5 rounded max-w-[160px] truncate hover:underline"
              title={project.address}
              data-testid={`mytasks-addr-${task.id}`}
            >
              {project.address.split(',')[0]}
            </Link>
          )}

          <span className="text-[9px] text-dim">{permitLabel}</span>

          {/* Status pill */}
          <StatusPill state={state} />

          {/* Due date */}
          {due && (
            <span
              className={`text-[9px] ${
                dueIsPastDue
                  ? 'text-[#dc2626] font-bold'
                  : dueRel && dueRel !== 'today' && dueRel.endsWith('d')
                    ? 'text-co font-semibold'
                    : 'text-de'
              }`}
              data-testid={`mytasks-due-${task.id}`}
            >
              ⊙ {due}
              {dueRel && <span className="ml-0.5">({dueRel})</span>}
            </span>
          )}

          {/* Assignee chip (v2 addition — surfaces the unified assigned_to) */}
          {task.assigned_to && (
            <span
              className="text-[9px] text-muted bg-s2 border border-border px-1 py-0.5 rounded"
              data-testid={`mytasks-assignee-${task.id}`}
            >
              {task.assigned_to}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

const STATE_PILL: Record<
  ReturnType<typeof deriveTaskState>,
  { label: string; cls: string }
> = {
  'not-started': {
    label: '○ Not Started',
    cls: 'text-dim',
  },
  'in-progress': {
    label: '◐ In Progress',
    cls: 'text-de font-semibold',
  },
  complete: {
    label: '● Done',
    cls: 'text-pm',
  },
};

function StatusPill({ state }: { state: ReturnType<typeof deriveTaskState> }) {
  const cfg = STATE_PILL[state];
  return <span className={`text-[9px] ${cfg.cls}`}>{cfg.label}</span>;
}
